Name:           ros-indigo-kobuki-qtestsuite
Version:        0.4.0
Release:        0%{?dist}
Summary:        ROS kobuki_qtestsuite package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/kobuki_qtestsuite
Source0:        %{name}-%{version}.tar.gz

Requires:       PyQt4-devel
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-kobuki-testsuite
Requires:       ros-indigo-nav-msgs
Requires:       ros-indigo-qt-gui-py-common
Requires:       ros-indigo-rospy
Requires:       ros-indigo-rqt-gui
Requires:       ros-indigo-rqt-gui-py
Requires:       ros-indigo-rqt-plot
Requires:       ros-indigo-rqt-py-common
BuildRequires:  PyQt4-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-kobuki-testsuite
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-qt-gui-py-common
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-rqt-gui
BuildRequires:  ros-indigo-rqt-gui-py
BuildRequires:  ros-indigo-rqt-plot
BuildRequires:  ros-indigo-rqt-py-common

%description
An rqt plugin that provides a graphical, interactive testsuite for Kobuki.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Aug 11 2014 Daniel Stonier <stonier@yujinrobot.com> - 0.4.0-0
- Autogenerated by Bloom

